version: "3.8"

services:
  namenode:
    image: "bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8"
    container_name: namenode
    environment:
      - CLUSTER_NAME=eth
      - PYSPARK_PYTHON=python3
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data/:/data/
    ports:
      - 9870:9870
      - 9000:9000

  datanode:
    image: "bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8"
    container_name: datanode
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - 3000:3000

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  spark_master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark_master
    ports:
      - 8080:8080
    environment:
      - PYSPARK_PYTHON=python3
    env_file:
      - ./hadoop.env

  spark_worker:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark_worker
    depends_on:
      - spark_master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./hadoop.env


volumes:
  hadoop_namenode:
  hadoop_datanode:
  mongo:
